// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	Delete(ctx context.Context, arg DeleteParams) error
	List(ctx context.Context) ([]ListRow, error)
	Push(ctx context.Context, arg PushParams) error
}

var _ Querier = (*Queries)(nil)
