// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"
)

const delete = `-- name: Delete :exec
DELETE FROM subscriptions
WHERE owner = $1 AND repo = $2
`

type DeleteParams struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) error {
	_, err := q.db.Exec(ctx, delete, arg.Owner, arg.Repo)
	return err
}

const list = `-- name: List :many
SELECT owner, repo FROM subscriptions
ORDER BY owner, repo
`

type ListRow struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

func (q *Queries) List(ctx context.Context) ([]ListRow, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRow
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(&i.Owner, &i.Repo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const push = `-- name: Push :exec
INSERT INTO subscriptions (owner, repo)
VALUES ($1, $2)
ON CONFLICT (owner, repo) DO NOTHING
`

type PushParams struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

func (q *Queries) Push(ctx context.Context, arg PushParams) error {
	_, err := q.db.Exec(ctx, push, arg.Owner, arg.Repo)
	return err
}
