// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: repo-stat/proto/subscribe/subscribe.proto

package subscribe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subscribe_Subscribe_FullMethodName   = "/subscribe.v1.Subscribe/Subscribe"
	Subscribe_Unsubscribe_FullMethodName = "/subscribe.v1.Subscribe/Unsubscribe"
	Subscribe_Subinfo_FullMethodName     = "/subscribe.v1.Subscribe/Subinfo"
)

// SubscribeClient is the client API for Subscribe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscribeClient interface {
	Subscribe(ctx context.Context, in *Data, opts ...grpc.CallOption) (*SubReply, error)
	Unsubscribe(ctx context.Context, in *Data, opts ...grpc.CallOption) (*SubReply, error)
	Subinfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoReply, error)
}

type subscribeClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscribeClient(cc grpc.ClientConnInterface) SubscribeClient {
	return &subscribeClient{cc}
}

func (c *subscribeClient) Subscribe(ctx context.Context, in *Data, opts ...grpc.CallOption) (*SubReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubReply)
	err := c.cc.Invoke(ctx, Subscribe_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribeClient) Unsubscribe(ctx context.Context, in *Data, opts ...grpc.CallOption) (*SubReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubReply)
	err := c.cc.Invoke(ctx, Subscribe_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribeClient) Subinfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoReply)
	err := c.cc.Invoke(ctx, Subscribe_Subinfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscribeServer is the server API for Subscribe service.
// All implementations must embed UnimplementedSubscribeServer
// for forward compatibility.
type SubscribeServer interface {
	Subscribe(context.Context, *Data) (*SubReply, error)
	Unsubscribe(context.Context, *Data) (*SubReply, error)
	Subinfo(context.Context, *Empty) (*InfoReply, error)
	mustEmbedUnimplementedSubscribeServer()
}

// UnimplementedSubscribeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscribeServer struct{}

func (UnimplementedSubscribeServer) Subscribe(context.Context, *Data) (*SubReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSubscribeServer) Unsubscribe(context.Context, *Data) (*SubReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedSubscribeServer) Subinfo(context.Context, *Empty) (*InfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Subinfo not implemented")
}
func (UnimplementedSubscribeServer) mustEmbedUnimplementedSubscribeServer() {}
func (UnimplementedSubscribeServer) testEmbeddedByValue()                   {}

// UnsafeSubscribeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscribeServer will
// result in compilation errors.
type UnsafeSubscribeServer interface {
	mustEmbedUnimplementedSubscribeServer()
}

func RegisterSubscribeServer(s grpc.ServiceRegistrar, srv SubscribeServer) {
	// If the following call panics, it indicates UnimplementedSubscribeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subscribe_ServiceDesc, srv)
}

func _Subscribe_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscribe_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeServer).Subscribe(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscribe_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscribe_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeServer).Unsubscribe(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscribe_Subinfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeServer).Subinfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscribe_Subinfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeServer).Subinfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Subscribe_ServiceDesc is the grpc.ServiceDesc for Subscribe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subscribe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscribe.v1.Subscribe",
	HandlerType: (*SubscribeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _Subscribe_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _Subscribe_Unsubscribe_Handler,
		},
		{
			MethodName: "Subinfo",
			Handler:    _Subscribe_Subinfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repo-stat/proto/subscribe/subscribe.proto",
}
