app:
  app_name: "repo-stat-collector"

grpc:
  address: "localhost:8084"
  timeout: "5s"

kafka:
  brokers: "kafka:9092"
  group: "collector-group"
  intopic: "collect-commands"
  outtopic: "collect-results"
  auto_update_interval: "15s"

logger:
  log_level: "DEBUG"

services:
  processor: "processor:8083"
  subscribe: "subscribe:8085"
