// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: repo-stat/proto/subscribe/subscribe.proto

package subscribe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_repo_stat_proto_subscribe_subscribe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_repo_stat_proto_subscribe_subscribe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_repo_stat_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Data) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_repo_stat_proto_subscribe_subscribe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_repo_stat_proto_subscribe_subscribe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_repo_stat_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{1}
}

type SubReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubReply) Reset() {
	*x = SubReply{}
	mi := &file_repo_stat_proto_subscribe_subscribe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubReply) ProtoMessage() {}

func (x *SubReply) ProtoReflect() protoreflect.Message {
	mi := &file_repo_stat_proto_subscribe_subscribe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubReply.ProtoReflect.Descriptor instead.
func (*SubReply) Descriptor() ([]byte, []int) {
	return file_repo_stat_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{2}
}

func (x *SubReply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type InfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Data                `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoReply) Reset() {
	*x = InfoReply{}
	mi := &file_repo_stat_proto_subscribe_subscribe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReply) ProtoMessage() {}

func (x *InfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_repo_stat_proto_subscribe_subscribe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReply.ProtoReflect.Descriptor instead.
func (*InfoReply) Descriptor() ([]byte, []int) {
	return file_repo_stat_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{3}
}

func (x *InfoReply) GetSubscriptions() []*Data {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_repo_stat_proto_subscribe_subscribe_proto protoreflect.FileDescriptor

const file_repo_stat_proto_subscribe_subscribe_proto_rawDesc = "" +
	"\n" +
	")repo-stat/proto/subscribe/subscribe.proto\x12\fsubscribe.v1\"0\n" +
	"\x04Data\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"\a\n" +
	"\x05Empty\" \n" +
	"\bSubReply\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"E\n" +
	"\tInfoReply\x128\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x12.subscribe.v1.DataR\rsubscriptions2\xbe\x01\n" +
	"\tSubscribe\x129\n" +
	"\tSubscribe\x12\x12.subscribe.v1.Data\x1a\x16.subscribe.v1.SubReply\"\x00\x12;\n" +
	"\vUnsubscribe\x12\x12.subscribe.v1.Data\x1a\x16.subscribe.v1.SubReply\"\x00\x129\n" +
	"\aSubinfo\x12\x13.subscribe.v1.Empty\x1a\x17.subscribe.v1.InfoReply\"\x00B\x1bZ\x19repo-stat/proto/subscribeb\x06proto3"

var (
	file_repo_stat_proto_subscribe_subscribe_proto_rawDescOnce sync.Once
	file_repo_stat_proto_subscribe_subscribe_proto_rawDescData []byte
)

func file_repo_stat_proto_subscribe_subscribe_proto_rawDescGZIP() []byte {
	file_repo_stat_proto_subscribe_subscribe_proto_rawDescOnce.Do(func() {
		file_repo_stat_proto_subscribe_subscribe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repo_stat_proto_subscribe_subscribe_proto_rawDesc), len(file_repo_stat_proto_subscribe_subscribe_proto_rawDesc)))
	})
	return file_repo_stat_proto_subscribe_subscribe_proto_rawDescData
}

var file_repo_stat_proto_subscribe_subscribe_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_repo_stat_proto_subscribe_subscribe_proto_goTypes = []any{
	(*Data)(nil),      // 0: subscribe.v1.Data
	(*Empty)(nil),     // 1: subscribe.v1.Empty
	(*SubReply)(nil),  // 2: subscribe.v1.SubReply
	(*InfoReply)(nil), // 3: subscribe.v1.InfoReply
}
var file_repo_stat_proto_subscribe_subscribe_proto_depIdxs = []int32{
	0, // 0: subscribe.v1.InfoReply.subscriptions:type_name -> subscribe.v1.Data
	0, // 1: subscribe.v1.Subscribe.Subscribe:input_type -> subscribe.v1.Data
	0, // 2: subscribe.v1.Subscribe.Unsubscribe:input_type -> subscribe.v1.Data
	1, // 3: subscribe.v1.Subscribe.Subinfo:input_type -> subscribe.v1.Empty
	2, // 4: subscribe.v1.Subscribe.Subscribe:output_type -> subscribe.v1.SubReply
	2, // 5: subscribe.v1.Subscribe.Unsubscribe:output_type -> subscribe.v1.SubReply
	3, // 6: subscribe.v1.Subscribe.Subinfo:output_type -> subscribe.v1.InfoReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_repo_stat_proto_subscribe_subscribe_proto_init() }
func file_repo_stat_proto_subscribe_subscribe_proto_init() {
	if File_repo_stat_proto_subscribe_subscribe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repo_stat_proto_subscribe_subscribe_proto_rawDesc), len(file_repo_stat_proto_subscribe_subscribe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repo_stat_proto_subscribe_subscribe_proto_goTypes,
		DependencyIndexes: file_repo_stat_proto_subscribe_subscribe_proto_depIdxs,
		MessageInfos:      file_repo_stat_proto_subscribe_subscribe_proto_msgTypes,
	}.Build()
	File_repo_stat_proto_subscribe_subscribe_proto = out.File
	file_repo_stat_proto_subscribe_subscribe_proto_goTypes = nil
	file_repo_stat_proto_subscribe_subscribe_proto_depIdxs = nil
}
