// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Info struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Stars       pgtype.Int4        `json:"stars"`
	Forks       pgtype.Int4        `json:"forks"`
	Date        pgtype.Timestamptz `json:"date"`
}
