// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const delete = `-- name: Delete :exec
DELETE FROM info
WHERE name = $1
`

func (q *Queries) Delete(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, delete, name)
	return err
}

const list = `-- name: List :many
SELECT name, description, stars, forks, date FROM info
ORDER BY name
`

func (q *Queries) List(ctx context.Context) ([]Info, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Info
	for rows.Next() {
		var i Info
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Stars,
			&i.Forks,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const push = `-- name: Push :exec
INSERT INTO info (name, description, stars, forks, date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name) 
DO UPDATE SET
    description = EXCLUDED.description,
    stars       = EXCLUDED.stars,
    forks       = EXCLUDED.forks,
    date        = EXCLUDED.date
`

type PushParams struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Stars       pgtype.Int4        `json:"stars"`
	Forks       pgtype.Int4        `json:"forks"`
	Date        pgtype.Timestamptz `json:"date"`
}

func (q *Queries) Push(ctx context.Context, arg PushParams) error {
	_, err := q.db.Exec(ctx, push,
		arg.Name,
		arg.Description,
		arg.Stars,
		arg.Forks,
		arg.Date,
	)
	return err
}
