// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: collector/proto/collector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_collector_proto_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_collector_proto_collector_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Data) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Stars         int32                  `protobuf:"varint,3,opt,name=Stars,proto3" json:"Stars,omitempty"`
	Forks         int32                  `protobuf:"varint,4,opt,name=Forks,proto3" json:"Forks,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=Date,proto3" json:"Date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_collector_proto_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_collector_proto_collector_proto_rawDescGZIP(), []int{1}
}

func (x *Repo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repo) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *Repo) GetForks() int32 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *Repo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_collector_proto_collector_proto protoreflect.FileDescriptor

const file_collector_proto_collector_proto_rawDesc = "" +
	"\n" +
	"\x1fcollector/proto/collector.proto\"0\n" +
	"\x04Data\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"|\n" +
	"\x04Repo\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Stars\x18\x03 \x01(\x05R\x05Stars\x12\x14\n" +
	"\x05Forks\x18\x04 \x01(\x05R\x05Forks\x12\x12\n" +
	"\x04Date\x18\x05 \x01(\tR\x04Date2&\n" +
	"\tCollector\x12\x19\n" +
	"\aGetInfo\x12\x05.Data\x1a\x05.Repo\"\x00B\x11Z\x0fcollector/protob\x06proto3"

var (
	file_collector_proto_collector_proto_rawDescOnce sync.Once
	file_collector_proto_collector_proto_rawDescData []byte
)

func file_collector_proto_collector_proto_rawDescGZIP() []byte {
	file_collector_proto_collector_proto_rawDescOnce.Do(func() {
		file_collector_proto_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collector_proto_collector_proto_rawDesc), len(file_collector_proto_collector_proto_rawDesc)))
	})
	return file_collector_proto_collector_proto_rawDescData
}

var file_collector_proto_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_collector_proto_collector_proto_goTypes = []any{
	(*Data)(nil), // 0: Data
	(*Repo)(nil), // 1: Repo
}
var file_collector_proto_collector_proto_depIdxs = []int32{
	0, // 0: Collector.GetInfo:input_type -> Data
	1, // 1: Collector.GetInfo:output_type -> Repo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collector_proto_collector_proto_init() }
func file_collector_proto_collector_proto_init() {
	if File_collector_proto_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collector_proto_collector_proto_rawDesc), len(file_collector_proto_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_proto_collector_proto_goTypes,
		DependencyIndexes: file_collector_proto_collector_proto_depIdxs,
		MessageInfos:      file_collector_proto_collector_proto_msgTypes,
	}.Build()
	File_collector_proto_collector_proto = out.File
	file_collector_proto_collector_proto_goTypes = nil
	file_collector_proto_collector_proto_depIdxs = nil
}
