syntax = "proto3";

package processor.v1;

option go_package = "repo-stat/proto/processor";

service Processor{
    rpc GetInfo(Data) returns (Repo);
    rpc GetSubInfo(Empty) returns (Repos) {};
    rpc Ping(PingRequest) returns (PingResponse);
}
message Data {
    string owner = 1;
    string repo = 2;
}
message Repo {
    string name = 1;
	string description = 2;
	int32 stars = 3;
	int32 forks = 4;
	string date = 5;
}
message PingRequest {
}
message PingResponse {
  string reply = 1;
}
message Empty{
}
message Repos{
    repeated Repo subscriptions = 1;
}